INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Gaurav', 'Jain', 25);

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Dhananjay', 'Jain', 15);

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Ram', 'More', 35);